### ISSUE TITLE
Couldn't connect to the master server, retrying in 30 seconds.

### ISSUE THREAD

**Issue by ghost** [AttorneyOnline/tsuserver3#40]
I got this error:
```bash
Couldn't connect to the master server, retrying in 30 seconds.
Exception ignored in: <coroutine object MasterServerClient.connect at 0x761c8a20>
Traceback (most recent call last):
  File "/home/pi/tsuserver3/server/masterserverclient.py", line 46, in connect
    await asyncio.sleep(30)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 480, in sleep
    future, result)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 544, in call_later
    timer = self.call_at(self.time() + delay, callback, *args)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 554, in call_at
    self._check_closed()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<MasterServerClient.connect() done, defined at /home/pi/tsuserver3/server/masterserverclient.py:30> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x761cc3b0>()]>>
```
*I am running it on a raspberry pi for keeping it on 24/7*

**Comment by mposs00** [comment]
Please ask on the discord before posting an issue. This could well be a configuration problem and the issue tracker is only for confirmed bugs.
